"""PIZDA

Revision ID: e5a9df3c8292
Revises: 
Create Date: 2024-04-08 14:10:53.388118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.currency


# revision identifiers, used by Alembic.
revision: str = "e5a9df3c8292"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sport_type",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("registration_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("registration_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("participation_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("participation_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("minimal_age", sa.Integer(), nullable=False),
        sa.Column("sport_type_id", sa.Uuid(), nullable=False),
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sport_type_id"],
            ["sport_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sport_type_translation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sport_type_id", sa.Uuid(), nullable=False),
        sa.Column("language_code", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sport_type_id"],
            ["sport_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "ticket_translation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("language_code", sa.String(length=5), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("extra_title", sa.String(), nullable=False),
        sa.Column(
            "price",
            sqlalchemy_utils.types.currency.CurrencyType(length=3),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["sport_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_localisation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("language_code", sa.String(length=5), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("about", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("banner_filename", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "language_code"),
    )
    op.create_table(
        "social_link",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticket",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("max_places", sa.Integer(), nullable=False),
        sa.Column("sport_type_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sport_type_id"],
            ["sport_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "article",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_translation_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_translation_id"],
            ["event_localisation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "starter_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_translation_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_translation_id"],
            ["event_localisation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticket_registation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("serial_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_registation")
    op.drop_table("starter_item")
    op.drop_table("article")
    op.drop_table("ticket")
    op.drop_table("social_link")
    op.drop_table("event_localisation")
    op.drop_table("document")
    op.drop_table("ticket_translation")
    op.drop_table("sport_type_translation")
    op.drop_table("event")
    op.drop_table("sport_type")
    # ### end Alembic commands ###
